### ISSUE TITLE
Por que ainda não estamos usando o php-cli ?

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/poste-mais#2]
Um tema falando sobre como usar mais o php-cli e seus benefícios.

**Comment by reginaldojunior** [comment]
https://medium.com/@reginaldojunior_55030/por-que-n%C3%A3o-php-cli-bb2a1254cb56

**Comment by ghost** [comment]
Acho que o que falta no PHP é um software de criação de [caixas de diálogo](https://en.wikipedia.org/wiki/Dialog_(software)) como o [ncurses](http://php.net/manual/pt_BR/book.ncurses.php) ou o [newt](https://en.wikipedia.org/wiki/Newt_(programming_library)). 

Tem uma extensão do ncurses em C [no PECL](http://pecl.php.net/package/ncurses) mas quem ainda usa o PECL hoje em dia? Até já existem alguns pacotes do ncurses no Packagist, mas são só wrappers:
- https://packagist.org/packages/wapmorgan/ncursesobjects
- https://packagist.org/packages/vsychov/php_ncurses

Outro motivos é que o Composer ainda não consegue ter um bom suporte para arquivos .phar. Precisa configurar variáveis de ambiente, permissões de execução, etc. Além disso é complicado e arriscado fazer e distribuir scripts nesse formato.

Recentemente fiz um [menu em Shell Script](https://github.com/aicoutos/basic/blob/master/make)  para rodar alguns scripts PHP. Estou pensando em refazer ele em whiptail que usa o newt e já vem junto no Ubuntu no CentOS.

<a href="http://i.imgur.com/XSfk5CP.png">
  <img src="http://imgur.com/XSfk5CPl.png" />
</a>
