### ISSUE TITLE
Cloud IDE deixe de assumir a infra

### ISSUE THREAD

**Issue by ptcmariano** [backend-br/poste-mais#5]
Criando uma aplicação web e desenvolvendo de qualquer máquina. Quais são os motivos para você assumir a infraestrutura no seu computador?

https://newbl0g.wordpress.com/2017/05/01/ambiente-de-desenvolvimento-integrado-na-nuvem-cloud-ide/

**Comment by reginaldojunior** [comment]
@ptcmariano Quais os tópicos para eu colocar nos labels?

**Comment by ptcmariano** [comment]
php devido ao exemplo

**Comment by reginaldojunior** [comment]
Feito! :dog:

**Comment by ptcmariano** [comment]
thanks 👍
